package com.example.api.domain.inspectedPost

import com.example.api.domain.post.Post
import java.time.LocalDateTime

class InspectedPost(
    val post: Post,
    val categoryName: String,
    val autoGeneratedTags: List<String>,
    val inspectedAt: LocalDateTime
) {

    companion object {
        fun generate(post: Post, categoryName: String, autoGeneratedTags: List<String>): InspectedPost {
            return InspectedPost(post, categoryName, autoGeneratedTags, LocalDateTime.now())
        }
    }
}