spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eda_kotlin?serverTimezone=Asia/Seoul
    username: sgs1159
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true