package com.example.api.producer

import com.example.api.adapter.originalpost.OperationType
import com.example.api.domain.inspectedPost.InspectedPost
import com.example.api.domain.post.Post
import com.fasterxml.jackson.annotation.JsonProperty
import java.time.LocalDateTime

data class InspectedPostMessage(
    @JsonProperty("id") val id: Long,
    @JsonProperty("payload") val payload: Payload? = null,
    @JsonProperty("operationType") val operationType: OperationType
) {
    fun toModel(): InspectedPost {
        return InspectedPost(
            payload!!.post,
            payload.categoryName,
            payload.autoGeneratedTags,
            payload.inspectedAt
        )
    }
}

data class Payload(
    @JsonProperty("post") val post: Post,
    @JsonProperty("categoryName") val categoryName: String,
    @JsonProperty("autoGeneratedTags") val autoGeneratedTags: List<String>,
    @JsonProperty("inspectedAt") val inspectedAt: LocalDateTime
)